# Generated by Django 5.2.8 on 2025-11-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffeeapp', '0002_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coffees/'),
        ),
    ]
